# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---
# Variables used in this pipeline are defined in `shared-pipeline-vars`, which is `source`'d before calling `buidkite-agent pipeline upload`

steps:
  - group: 'Code Quality Checks'
    key: quality-checks
    steps:
      - label: '🕵️ Linting & Formatting'
        key: quality-check
        plugins: [$NVM_PLUGIN]
        command: |
          echo "--- 📦 Installing dependencies"
          npm ci
          echo "--- 🕵️ Running linting checks"
          npm run lint
          echo "--- 🕵️ Running formatting checks"
          npm run format:check
        notify:
          - github_commit_status:
              context: Lint & Formatting Check

      - label: '🔍 Type Checking'
        key: type-check
        plugins: [$NVM_PLUGIN]
        command: |
          echo "--- 📦 Installing dependencies"
          npm ci
          echo "--- 🔍 Running TypeScript type checking"
          npx tsc --noEmit
        notify:
          - github_commit_status:
              context: Type Checking

  - group: 'Tests'
    key: all-tests
    steps:
      - label: '🧪 Unit Tests'
        key: unit-tests
        plugins: [$NVM_PLUGIN]
        command: |
          echo "--- 📦 Installing dependencies"
          npm ci
          echo "--- 🧪 Running unit tests"
          npm run test:unit
        notify:
          - github_commit_status:
              context: Unit Tests

      - label: '🔄 Integration Tests'
        key: integration-tests
        plugins: [$NVM_PLUGIN]
        command: |
          echo "--- 📦 Installing dependencies"
          npm ci
          echo "--- 🔄 Running integration tests"
          npm run test:integration
        notify:
          - github_commit_status:
              context: Integration Tests

      - label: '🌐 End-to-End Tests'
        key: e2e-tests
        plugins: [$NVM_PLUGIN]
        command: |
          echo "--- 📦 Installing dependencies"
          npm ci
          echo "--- 🌐 Running end-to-end tests"
          npm run test:e2e
        notify:
          - github_commit_status:
              context: End-to-End Tests

  - label: '📊 Test Coverage'
    key: test-coverage
    depends_on: all-tests
    plugins: [$NVM_PLUGIN]
    command: |
      echo "--- 📦 Installing dependencies"
      npm ci
      echo "--- 📊 Generating test coverage report"
      npm run test:coverage
    artifact_paths:
      - 'coverage/**/*'
    notify:
      - github_commit_status:
          context: Test Coverage

  - label: '🔍 MCP Server Build and Run'
    key: server-launch-test
    depends_on: all-tests
    plugins: [$NVM_PLUGIN]
    command: |
      echo "--- 📦 Installing dependencies"
      npm ci
      .buildkite/commands/test-run-server.sh
    notify:
      - github_commit_status:
          context: MCP Server
