# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---
# Variables used in this pipeline are defined in `shared-pipeline-vars`, which is `source`'d before calling `buildkite-agent pipeline upload`

steps:
  # Phase 1: Code Quality & Tests (Parallel)
  - label: "✨ Code Quality (Node {{matrix.node}})"
    key: quality
    matrix:
      setup:
        node:
         - '20'
         - '22'
         - '24'
    plugins:
      - $NVM_PLUGIN:
          version: "{{matrix.node}}"
    command: |
      echo "--- 📦 Installing dependencies (Node {{matrix.node}})"
      npm ci
      echo "--- 🕵️ Running linting checks"
      npm run lint
      echo "--- 🕵️ Running formatting checks"
      npm run format:check
      echo "--- 🔍 Running TypeScript type checking"
      npm run type-check
    notify:
      - github_commit_status:
          context: "Code Quality"

  - label: "🧪 Tests (Node {{matrix.node}})"
    key: tests
    matrix:
      setup:
        node:
         - '20'
         - '22'
         - '24'
    plugins:
      - $NVM_PLUGIN:
          version: "{{matrix.node}}"
    command: |
      echo "--- 📦 Installing dependencies (Node {{matrix.node}})"
      npm ci
      echo "--- 🧪 Running all tests"
      npm test
    notify:
      - github_commit_status:
          context: "Tests"

  # Phase 2: Build & Run (After quality and tests pass)
  - label: "🔍 Build & Run (Node {{matrix.node}})"
    key: server
    matrix:
      setup:
        node:
         - '20'
         - '22'
         - '24'
    depends_on:
      - quality
      - tests
    plugins:
      - $NVM_PLUGIN:
          version: "{{matrix.node}}"
    command: |
      echo "--- 📦 Installing dependencies (Node {{matrix.node}})"
      npm ci
      .buildkite/commands/test-run-server.sh
    notify:
      - github_commit_status:
          context: "Build & Run"

  # Phase 3: Publish to NPM (Only on semantic version tags)
  - label: "📦 Publish to NPM"
    key: "publish"
    depends_on:
      - "quality"
      - "tests"
      - "server"
    if: build.tag =~ /^v\d+\.\d+/
    env:
      NPM_TOKEN: $NPM_TOKEN
    plugins:
      - $NVM_PLUGIN:
          version: "20"
    command: |
      echo "--- 📦 Installing dependencies"
      npm ci
      echo "--- 🚀 Publishing to NPM (build happens automatically via prepare script)"
      npm publish
    notify:
      - github_commit_status:
          context: "NPM Publish"
